### ISSUE TITLE
pathlib.Path.rglob is recursive but etils.epath.Path.rglob isn't

### ISSUE THREAD

**Issue by carlthome** [google/etils#167]
Was trying to add gs://... support to a TFDS builder that was working with local files, and figured I'd try to simply replace `pathlib` with `etils.epath` since it was already in `tfds.core.Path` and would involve minimal changes.

Unfortunately got tripped up on 

>AssertionError: Not a single example present in the PCollection! [while running 'test_write/GetBoundaries']

which seems to be caused by `rglob` not actually being recursive, as per: https://github.com/google/etils/blob/main/etils/epath/abstract_path.py#L111

Mentioning this here just in case anyone else got confused by the same thing.

## Example
```py
In [1]: import pathlib

In [2]: import etils.epath

In [3]: list(etils.epath.Path('.').rglob("*.py"))
Out[3]: [PosixGPath('builders/__init__.py')]

In [4]: list(pathlib.Path('.').rglob("*.py"))
Out[4]: 
[PosixPath('builders/__init__.py'),
 PosixPath('builders/my_dataset/my_dataset_test.py'),
 PosixPath('builders/my_dataset/my_dataset.py'),
 PosixPath('builders/my_dataset/__init__.py')]
```

**Comment by carlthome** [comment]
>I believe the rational given is that it could accidentally trigger thousands of RPC request when used on GCS path, and the Google Cloud Storage is not really designed to support those calls.

Ah, figured it was something about limitations of the underlying object storage not being a hierarchical filesystem. Having a more helpful error message to point out this discrepancy is much appreciated! :clap: 

**Thinking out loud:**
Would be convenient to have recursive globbing though (for use cases like "give me every *.jpg from this root directory down").

Maybe by initially listing the entire bucket to a local index structure like  `~/.cache/epath/buckets/*.parquet` (or similar), and caching such an index locally with a configurable TTL (to eventually re-list and find new blobs too), and having `rglob` and friends look through the local index. Big can of worms though. Maybe best to think about this in https://github.com/tensorflow/tensorflow/issues/39565 instead of here. Closing!

**Comment by Conchylicultor** [comment]
Yes, I agree this would be nice to have, which is why I wasn't sure to closed the issue yet.
But I agree this is more a TF issue than an `epath` one.
