### ISSUE TITLE
Using etils's `epath` with AWS S3 links

### ISSUE THREAD

**Issue by neel04** [google/etils#168]
Hey,

Apparently, one can't use S3 objects with etils:
```py
from etils import epath
a = epath.Path( 's3://....' ) #link points to a folder of .tfrecords
sorted(epath.Path('s3://..').iterdir())
```

### Error
Yields,
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/etils/epath/gpath.py", line 126, in iterdir
    for f in self._backend.listdir(self._path_str):
  File "/usr/local/lib/python3.8/dist-packages/etils/epath/backend.py", line 191, in listdir
    return self.gfile.listdir(path)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/lib/io/file_io.py", line 766, in list_directory_v2
    raise errors.NotFoundError(
tensorflow.python.framework.errors_impl.NotFoundError: Could not find directory s3://..
```

This utilized in [TFDS](https://github.com/tensorflow/datasets/blob/1ef4c0652186adea3cffa15ce60d4f70d32a8fca/tensorflow_datasets/core/folder_dataset/compute_split_utils.py#L110-L112) simply to compute some meta-data for the datasets I'd be working in. 

I can confirm the given link exists when copypasted to the `aws s3 ls s3://....` command. It seems an issue with `etils`, or I'm using it wrongly.

Cheers!

**Comment by neel04** [comment]
I assume `epath`, because the tracebacks are same
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/awesome/.local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 769, in list_directory_v2
    message="Could not find directory {}".format(path))
tensorflow.python.framework.errors_impl.NotFoundError: Could not find directory s3://s-laion/ssd-videos/new_tfrecs/
```

**Comment by Conchylicultor** [comment]
If you also get the same error using only `tf.io.gfile` (without `epath`), it means the error is coming from TensorFlow, not epath, right ? Or I have misunderstood something ?

**Comment by neel04** [comment]
Fair enough; I'd opened an issue with TF but they weren't helpful; ultimately resolved with downgrading. 
I'm trying to use with `TFDS` but have been facing a barrage of errors with S3 😞 absolutely plagued by `No response body`, Trying for days to resolve this; kinda regretting using TF over PyTorch.

Thanks for your help though.
