### ISSUE TITLE
pip installing etils spews warnings

### ISSUE THREAD

**Issue by pwais** [google/etils#185]
I've tried doing a `pip3 install etils[all]` and then running a subsequent command that installs jax and by trans deps etils, and I get this error polluting the terminal:
```
WARNING: etils 0.2.0 does not provide the extra 'edc'
WARNING: etils 0.3.3 does not provide the extra 'edc'
WARNING: etils 0.3.2 does not provide the extra 'edc'
WARNING: etils 0.3.1 does not provide the extra 'edc'
WARNING: etils 0.3.0 does not provide the extra 'edc'
WARNING: etils 0.2.0 does not provide the extra 'edc'
WARNING: etils 0.3.3 does not provide the extra 'edc'
WARNING: etils 0.3.2 does not provide the extra 'edc'
WARNING: etils 0.3.1 does not provide the extra 'edc'
WARNING: etils 0.3.0 does not provide the extra 'edc'
WARNING: etils 0.2.0 does not provide the extra 'edc'
WARNING: etils 0.3.3 does not provide the extra 'edc'
WARNING: etils 0.3.2 does not provide the extra 'edc'
WARNING: etils 0.3.1 does not provide the extra 'edc'
WARNING: etils 0.3.0 does not provide the extra 'edc'
WARNING: etils 0.2.0 does not provide the extra 'edc'
WARNING: etils 0.3.3 does not provide the extra 'edc'
```

Can't you just integrate your code into jax or something?  this lib has ELEVEN different sub-targets. you are creating a dependency game that really really nobody wants.  at the very least please consider a way to silence this error, even if it means minimizing your package structure and getting your code into upstream.

**Comment by Conchylicultor** [comment]
Thanks for the feedback. The plan for etils is to be the home of various self-contained utils without having to create a new independent project each time.

Once one of those util become mature enough, they can be moved to their own self-contained project. Indeed this seemed like a good idea for `epath` (though I do not own the `epath` PyPI project, so I might have to rename it).

I'm confused though why you have to call `pip install etils[all]` manually. Installing `pip install jax` should install the required `etils` deps. Also I wasn't able to reproduce the issue. etils is at version `0.6.0` so not sure why your PyPI try to install `0.3.3`.

**Comment by pwais** [comment]
I was trying to install an older version of jax to run some research code, and I guess that jax / project referenced 0.3.3.

The root problem here is that etils has so many sub-targets.  For enterprise users, I'm sure there's patience for such a complicated build, but for research, this sort of ancillary complexity is a non-starter.  I'm not a Googler, but I'm pretty sure this library violates the design recommendation of "don't try to do too many things in one library."  I guess this project grew organically due to these sorts of problems: https://www.youtube.com/watch?v=3t6L-FlfeaI  

i dunno, I'm gonna stick to pytorch. I can barely get Jax to work with modern GPUs....
