### ISSUE TITLE
When using edc and frozen/unfrozen pylint and mypy complain

### ISSUE THREAD

**Issue by andylamp** [google/etils#193]
Hello,

Thanks for the cool library. When using the `edc` module and un particular `frozen`/`unfrozen` function both `mypy` and `pylint` complain about types.

This is fairly easy to reproduce, just by using the following snippet:

```python
from dataclasses import dataclass
from etils import edc

@edc.dataclass(allow_unfrozen=True)
@dataclass(frozen=True)
class MyConf:
	my_var: str = "epic"

if __name__ == "__main__":
    qqq = MyConf(my_var="ff")
    
    # pylint and mypy complain!
    fff = qqq.unfrozen()
    ppp = fff.frozen()
```

Specifically `pylint` has the following output:

```text
E1101: Instance of 'MyConf' has no 'unfrozen' member (no-member)
```

whereas `mypy` gives:

```text
"MyConf" has no attribute "unfrozen"  [attr-defined]
```

I suspect both are for the same reason... is there a clean way (without ignoring these) to use this module while making both `mypy` and `pylint` happy?

For what is worth - I am using Ubuntu 22.04, python 3.10, pylint 2.14.5, and mypy 0.971.

**Comment by Conchylicultor** [comment]
Yes, unfortunately, this is a limitation of Python typing system, there's no way to indicate that a decorator add attributes to a class.

Ideally, I would want to annotate `edc.dataclass` using `Intersection` something like:

```python
ClsT = TypeVar('ClsT')

class Unfrozen(Protocol):
  def frozen(self) -> Self: ...
  def unfrozen(self) -> Self: ...


def dataclass(allow_unfrozen: bool = True) -> Callable[[ClsT], ClsT & Unfrozen]
```

Unfortunately, `Intersection` are not yet supported by Python.
You could upvote/comment https://github.com/python/typing/issues/213 so this get prioritised

In the meantime, you can manually disable the warning, like:

```python
fff = qqq.unfrozen()  # pylint: disable=no-member  # type: ignore[attr-defined]
```

**Comment by andylamp** [comment]
ah, thought so but wanted to check if there was another way - bummer! thanks for the reply!
