### ISSUE TITLE
etils.epath.Path.glob() removes gs:// prefix

### ISSUE THREAD

**Issue by simdasch** [google/etils#448]
I am trying to iterate over a "directory" in a bucket using glob(). Unfortunately the returned object Path objects are missing the gs:// part:

```
dir = Path(
        "gs://gcp-public-data-arco-era5/ar/1959-2022-1h-240x121_equiangular_with_poles_conservative.zarr/lake_depth"
    )
files = list(dir.glob("*"))
files[0].read_bytes() # fails with FileNotFoundError
```

Is this intended behavior?

**Comment by Conchylicultor** [comment]
What is the `files[0]` ? I would assume this is a directory, thus `read_bytes()` fail. Can you check `p.exists()` and `p.is_file()` works ?

**Comment by simdasch** [comment]
Hi @Conchylicultor,

Thanks for your reply.
files[0] seems to be a file:

```
from etils.epath import Path

dir = Path(
    "gs://gcp-public-data-arco-era5/ar/1959-2022-1h-240x121_equiangular_with_poles_conservative.zarr/lake_depth"
)
files = list(dir.glob("*"))
p = files[0]
p.is_file()  # -> True
p.exists()  # -> False
print(p)  # -> gcp-public-data-arco-era5/ar/1959-2022-1h-240x121_equiangular_with_poles_conservative.zarr/lake_depth/.zarray
p.read_bytes()  # fails with FileNotFoundError
```

![image](https://github.com/google/etils/assets/46324207/8c8cefd4-b201-46f1-ad9b-7757e66403b3)

In the line `print(p)` I would have expected that the name starts with "gs://" but it doesn't. The Path.iterdir() does behave differently:

```
files_iter = list(dir.iterdir())
p_iter = files_iter[0]
p_iter.is_file()  # -> True
p_iter.exists()  # -> True
print(p_iter)  # -> gs://gcp-public-data-arco-era5/ar/1959-2022-1h-240x121_equiangular_with_poles_conservative.zarr/lake_depth/.zarray
#                   ^^^^^
p_iter.read_bytes()  # returns bytes
```

BTW: I just chose a random public GCS object.

**Comment by Conchylicultor** [comment]
Thank you for reporting. Indeed, it seems an issue from the ffspec backend. Sending a fix now

```python
import fsspec

fs = fsspec.filesystem('gcs')

fs.glob('gs://tfds-data/datasets') == ['tfds-data/datasets/abc', ...]  # No gs:// prefix
```
