### ISSUE TITLE
`epath.Path("s3://...")` regression in python3.12?

### ISSUE THREAD

**Issue by Sibgatulin** [google/etils#607]
Hi there. I am not at all sure if it is not a misunderstanding or a misconfiguration on my end, but I am seeing different behaviour of `epath.Path` with s3 (at least) on python 3.11 and 3.12. Please, consider the attached screenshot for details.

![swappy-20240521_193845-cropped](https://github.com/google/etils/assets/10868826/7de1d755-dfe4-403a-9d7c-f33f8bc7f8f6)

Both of the environments are minimal with the following package versions:
```
Package             Version
------------------- -----------
aiobotocore         2.13.0
aiohttp             3.9.5
aioitertools        0.11.0
aiosignal           1.3.1
attrs               23.2.0
boto3               1.34.106
botocore            1.34.106
etils               1.8.0
frozenlist          1.4.1
fsspec              2024.5.0
idna                3.7
importlib_resources 6.4.0
jmespath            1.0.1
multidict           6.0.5
pip                 24.0
python-dateutil     2.9.0.post0
s3fs                2024.5.0
s3transfer          0.10.1
six                 1.16.0
typing_extensions   4.11.0
urllib3             2.2.1
wrapt               1.16.0
yarl                1.9.4
```
(with the addition of `setuptools==69.2.0` and `wheel==0.43.0` in `test311`).

**Comment by Conchylicultor** [comment]
Thanks for reporting the issue. `epath` is a small wrapper around `fsspec` and `s3fs` (for the s3:// backend).

Could you try to reproduce the issue directly with `fsspec`:

```python
import fsspec

fs = fsspec.filesystem('s3')

print(fs.exists('s3://aaa/test'))
```

If so, I would report this directly in https://github.com/fsspec/s3fs/issues, as we cannot fix this from the etils side.

**Comment by Sibgatulin** [comment]
Thanks for the quick reply @Conchylicultor!
Unfortunately, I cannot reproduce it with `fsspec` and your snippet appears to execute equally correctly with both 3.11 and 3.12. And yet, `epath.Path` still does not. The following code

```python
path_as_str = f"s3://{BUCKET_NAME}/test"
print(f"{fsspec.filesystem('s3').exists(path_as_str)=}")
print(f"{Path(path_as_str).exists()=}")
```
on 3.11 yields 
```
fsspec.filesystem('s3').exists(path_as_str)=True
Path(path_as_str).exists()=True
```
while on 3.12:
```
fsspec.filesystem('s3').exists(path_as_str)=True
Path(path_as_str).exists()=False
```

Would you imagine that it may be of any significance that `epath.Path.__fspath__` yiels `s3://...` on 3.11 vs `s3:/...` on 3.12 (see the screenshot above)?


It looks like in 3.11, `Path('s3://aaa/test').parts` yields `('/', 's3', 'aaa', 'test')` which results in `Path('s3://aaa/test')._uri_scheme` being correctly identified as `'s3'`. 
In 3.12, however, `Path('s3://aaa/test').parts` yields `('s3:', 'aaa', 'test')`, (same as `pathlib.Path('s3://aaa/test').parts`) [failing this condition](https://github.com/google/etils/blob/9b954639d16d6aa130570c001cf89c575151974b/etils/epath/gpath.py#L107), resulting in `._uri_scheme` returning `None`. 
Not sure if it is the root cause, but it also does not seem quite right to me... I am failing to find the definition of `.parts` right now though.

**Comment by ayaka14732** [comment]
I encountered the same problem for `gs://` and updating to the latest etils version has fixed for me

**Comment by Conchylicultor** [comment]
Marking this as closed as the fix has been released. Thank you all for reporting and the fix
